[tool.poetry]
name = "ml_hitwh"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [
    { include = "ml_hitwh", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7.3"
nonebot2 = "^2.0.0-beta.5"
nonebot-adapter-onebot = "^2.1.3"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.40"}
asyncpg = "^0.26.0"
tzlocal = "^4.2"
nonebot_plugin_apscheduler = "^0.1.3"

[tool.poetry.dev-dependencies]
nonebug = "^0.2.1"
aiosqlite = "^0.17.0"
sqlalchemy2-stubs = "^0.0.2a29"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
secondary = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
