[tool.poetry]
name = "nonebot-plugin-mahjong-scoreboard"
version = "0.5.0"
description = "日麻寄分器（NoneBot插件）"
authors = ["ssttkkl <huang.wen.long@hotmail.com>"]
readme = "README.MD"
license = "MIT"
repository = "https://github.com/ssttkkl/nonebot-plugin-mahjong-scoreboard"
packages = [
    { include = "nonebot_plugin_mahjong_scoreboard", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
nonebot2 = "^2.0.0"
nonebot-adapter-onebot = "^2.2.2"
nonebot-plugin-gocqhttp-cross-machine-upload-file = "^0.1.5"
nonebot-plugin-session = ">=0.0.3"
tzlocal = "^5.0.1"
cachetools = "^5.2.0"
mahjong-scoreboard-model = {git = "https://github.com/ssttkkl/mahjong-scoreboard-model.git"}
httpx = "^0.24.1"
injector = "^0.20.1"

[tool.poetry.group.dev.dependencies]
nonebot2 = { extras = ["httpx", "fastapi"], version = "^2.0.0rc3" }
nonebot-adapter-qqguild = "^0.2.2"
nonebug = "^0.2.1"
flake8 = "^5.0.4"
setuptools = "^68.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
